using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.ExceptionHandling
{
    class ExceptionClasses
    {
        /*
         * C# exceptions are represented by classes
         * 
         * exception classes in C# are mainly directly or indirectly derived from the "System.Exception" class
         * 
         * The System.ApplicationException class 
         *      supports exceptions generated by application programs
         *      Hence the exceptions defined by the programmers should derive from this class.
         * 
         * The System.SystemException class 
         *      is the base class for all predefined system exception.
         * 
         * 
            System.IO.IOException
                Handles I/O errors

            System.IndexOutOfRangeException
                Handles errors generated when a method refers to an array index out of range.

            System.ArrayTypeMismatchException
                Handles errors generated when type is mismatched with the array type.

            System.NullReferenceException
                Handles errors generated from referencing a null object.

            System.DivideByZeroException
                Handles errors generated from dividing a dividend with zero.

            System.InvalidCastException
                Handles errors generated during typecasting.

            System.OutOfMemoryException
                Handles errors generated from insufficient free memory.

            System.StackOverflowException
                Handles errors generated from stack overflow.
         */
        public static void Example()
        {

        }
    }
}
